server:
  port: 9887
spring:
  application:
    name: spcloud-ali-dubbo-provider-9887
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
dubbo:
  application:
    name: spcloud-ali-dubbo-provider-9887-dubbo #dubbo服务名
  protocol:
    #name: dubbo #协议名称
    name: tri #协议名称，triple协议填写的是tri，不是triple
    #host: localhost #本机ip地址
    #协议端口，指定dubbo服务的tcp端口
    #默认为20880，设置-1表示从20880开始自增端口，避免端口冲突
    # port: 8887
    port: -1
  registry: #配置并启用 Nacos
    address: nacos://localhost:8848
    # Dubbo3 默认采用 “应用级服务发现 + 接口级服务发现” 的双注册模式
    # 因此会发现应用级服务（应用名）和接口级服务（接口名）同时出现在nacos控制台
    # 可以通过配置 register-mode来改变注册行为，interface为接口级服务发现
    #register-mode: interface
  scan: #Dubbo服务实现类扫描基准包的位置
    base-packages: com.bleachin.** #扫描的接口包位置
#  monitor:
#    protocol: registry # 监控中心配置，从注册中心发现监控中心地址

#配置暴露所有的监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'


