server:
  port: 9886
spring:
  application:
    name: spcloud-ali-dubbo-provider-9886
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
dubbo:
  application:
    name: spcloud-ali-dubbo-provider-9886-dubbo #dubbo服务名
  protocol:
    #name: dubbo #协议名称
    name: tri #协议名称，triple协议填写的是tri，不是triple
    #host: localhost #本机ip地址
    #协议端口，指定dubbo服务的tcp端口
    #默认为20880，设置-1表示从20880开始自增端口，避免端口冲突
    # port: 8886
    port: -1
  registry: #配置并启用 Nacos
    #Dubbo3.0.0版本以后，增加了是否注册消费者的参数
    #如果需要将消费者注册到nacos上设置为true，默认是false。
    #加上这个参数后dubbo-admin才能看到我们的消费者
    address: nacos://localhost:8848?register-consumer-url=true
#  monitor:
#    protocol: registry # 监控中心配置，从注册中心发现监控中心地址

#配置暴露所有的监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'


